### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by bunkbail** [k4yt3x/video2x#1192]
I'm new to video2x and I'm trying to use anime4k via libplacebo, no matter what I do the program will crash due to out of memory situation. I've only tried version 6.0.0-beta3. I've tested both Qt GUI version on Windows and CLI version on Linux via Docker. Video process managed to go further on Linux due to swap space but OOM will occur regardless. I have 16gb of RAM (same amount of swap) and I saw the process memory usage grew up to 32gb before OOM hits on Linux.

**Comment by bunkbail** [comment]
A workaround I'm using right now is to split the original files into chunks of 1 min videos and process them that way. Every relaunches of video2x will reset the memory consumption so the leak won't be happening while processing each chunks. Here's a sample script that I'm using right now:
https://gist.github.com/bunkbail/c573be00d4640779742511e8b1bbfacc

**Comment by k4yt3x** [comment]
Interesting. Could you provide the command used? I'll profile the code with valgrind.

**Comment by bunkbail** [comment]
this is what i use on docker:

`docker run --gpus all --privileged -it --rm -v $PWD/data:/host -v /home/bunkbail/video2x-docker/videos:/videos   -v /home/bunkbail/video2x-docker/output:/output ghcr.io/k4yt3x/video2x:6.0.0-beta.3 -i /videos/Sleepy\ Princess\ in\ the\ Demon\ Castle\ -\ S01E01.mkv   -o /output/Sleepy\ Princess\ in\ the\ Demon\ Castle\ -\ S01E01.mkv   -f libplacebo -s anime4k-mode-a -w 1920 -h 1080 -c libx265 -p medium -q 22
`

but the GUI version on windows also suffers from the same thing

**Comment by k4yt3x** [comment]
I ran it for a five-minute ish video and I'm not seeing any major leaks. I don't think the definitely lost one is from my code either. Even if it is, it's only 192 bytes.

![image](https://github.com/user-attachments/assets/552624e4-7271-4bba-973b-6a3aa884093f)

Can you monitor the memory usage situation over time in your task manager or something and provide more details? So far I haven't been able to reproduce the issue.

**Comment by k4yt3x** [comment]
I've also monitored the memory usage. It consumed 5G of RAM pretty consistently. It's really interesting you're experiencing OOM issues. I wonder what went wrong.

![image](https://github.com/user-attachments/assets/e7c3ad03-c140-4025-9781-b28586f48f09)

**Comment by bunkbail** [comment]
So if I use a common anime episode as input (as you can see from the above I use "Sleepy Princess in the Demon Castle"), I can see the video2x will start using 2gb right off the bat and it will increase 200MB or so of memory usage per sec until it finished processing the whole video. That's why making chunks of 60s of videos works as a workaround. Maybe you wanna try the file I use to see if you can replicate my issue? I took the files from [here](https://nyaa.si/view/1594845). I don't think the issue lies with my Linux system either seeing how it does the same exact thing on Windows as well. 

 My pc specs: Ryzen 5 5600X and RX 6900 XT

**Comment by k4yt3x** [comment]
I'll give that a try. It might be an AMD thing. All my GPUs right now except for an RX580 sitting somewhere collecting dust are NVIDIA since I need CUDA a lot of the time. I'll also have a friend who has a 6900XT to try it.

**Comment by bunkbail** [comment]
I tried new sources (x264) and couldn't reproduce the memory leak. Perhaps the video2x beta can't handle x265 sources? You should try the file mentioned above to see if you can reproduce it or not.

**Comment by k4yt3x** [comment]
I might have found the leak. It might be an upstream bug

![image](https://github.com/user-attachments/assets/2abefd94-e5a8-4bbc-bb3a-00c9bb306671)

**Comment by k4yt3x** [comment]
I reviewed it and I didn't quite find a leak. I also tested using the videos you suggested and it's not really a "leak." Seems like it's just using a LOT of RAM (23G) for some reason.  You can see the memory consumption is relatively stable after a while:

![image](https://github.com/user-attachments/assets/9ee8aad8-be31-4cc5-9213-c1c80ed74d7c)

Honestly I'm confused where it's using all that RAM...

**Comment by k4yt3x** [comment]
OK I think I'm finally able to reproduce the issue. RealESRGAN actually doesn't have a problem. It's only when you're using libplacebo, it triggers a bug in the encoder that leaks a frame. I've fixed it and it'll be in the next release.

![image](https://github.com/user-attachments/assets/2c98a3b0-843a-4a07-8888-03fce829319e)

```diff
diff --git a/src/encoder.cpp b/src/encoder.cpp
index 5c35a5f..0486e75 100644
--- a/src/encoder.cpp
+++ b/src/encoder.cpp
@@ -183,18 +183,18 @@ int encode_and_write_frame(
     AVFormatContext *ofmt_ctx,
     int vstream_idx
 ) {
+    AVFrame *converted_frame = nullptr;
     int ret;
 
     // Convert the frame to the encoder's pixel format if needed
     if (frame->format != enc_ctx->pix_fmt) {
-        AVFrame *converted_frame = convert_avframe_pix_fmt(frame, enc_ctx->pix_fmt);
+        converted_frame = convert_avframe_pix_fmt(frame, enc_ctx->pix_fmt);
         if (!converted_frame) {
             spdlog::error("Error converting frame to encoder's pixel format");
             return AVERROR_EXTERNAL;
         }
 
         converted_frame->pts = frame->pts;
-        frame = converted_frame;
     }
 
     AVPacket *enc_pkt = av_packet_alloc();
@@ -203,7 +203,12 @@ int encode_and_write_frame(
         return AVERROR(ENOMEM);
     }
 
-    ret = avcodec_send_frame(enc_ctx, frame);
+    if (converted_frame != nullptr) {
+        ret = avcodec_send_frame(enc_ctx, converted_frame);
+        av_frame_free(&converted_frame);
+    } else {
+        ret = avcodec_send_frame(enc_ctx, frame);
+    }
     if (ret < 0) {
         spdlog::error("Error sending frame to encoder");
         av_packet_free(&enc_pkt);
```

**Comment by k4yt3x** [comment]
Thanks for the bug report.

**Comment by bunkbail** [comment]
Thanks for fixing it!

**Comment by derfurkan** [comment]
I still have an issue with this libplacebo is still leaking GPU Memory and crashing when its full.
